In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
dates = pd.date_range('20130101', periods=6)

In [4]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

In [6]:
df

A         B         C         D
2013-01-01 -0.243544 -0.462710 -2.429197 -0.451577
2013-01-02  1.759290 -0.483506 -0.257713  1.979433
2013-01-03 -1.291636 -0.900783 -0.522704  1.027194
2013-01-04  0.625595  2.412614  1.010998 -0.098321
2013-01-05  0.315964  1.159868  0.109759 -0.321938
2013-01-06 -0.219220  1.028138 -1.717185 -0.006148

In [7]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.243544    1.759290   -1.291636    0.625595    0.315964   -0.219220
B   -0.462710   -0.483506   -0.900783    2.412614    1.159868    1.028138
C   -2.429197   -0.257713   -0.522704    1.010998    0.109759   -1.717185
D   -0.451577    1.979433    1.027194   -0.098321   -0.321938   -0.006148

In [8]:
df.head()

A         B         C         D
2013-01-01 -0.243544 -0.462710 -2.429197 -0.451577
2013-01-02  1.759290 -0.483506 -0.257713  1.979433
2013-01-03 -1.291636 -0.900783 -0.522704  1.027194
2013-01-04  0.625595  2.412614  1.010998 -0.098321
2013-01-05  0.315964  1.159868  0.109759 -0.321938

In [9]:
type(np.asarray(df.to_dense()))

numpy.ndarray

In [10]:
np.asarray(df.to_dense())

array([[-0.24354359, -0.46270995, -2.42919668, -0.45157666],
       [ 1.75928973, -0.48350609, -0.25771281,  1.97943305],
       [-1.29163614, -0.90078285, -0.52270411,  1.0271939 ],
       [ 0.62559549,  2.41261356,  1.01099843, -0.09832146],
       [ 0.31596425,  1.15986789,  0.10975856, -0.32193776],
       [-0.21921991,  1.02813838, -1.71718477, -0.00614837]])

In [11]:
df.values

array([[-0.24354359, -0.46270995, -2.42919668, -0.45157666],
       [ 1.75928973, -0.48350609, -0.25771281,  1.97943305],
       [-1.29163614, -0.90078285, -0.52270411,  1.0271939 ],
       [ 0.62559549,  2.41261356,  1.01099843, -0.09832146],
       [ 0.31596425,  1.15986789,  0.10975856, -0.32193776],
       [-0.21921991,  1.02813838, -1.71718477, -0.00614837]])

In [12]:
df

A         B         C         D
2013-01-01 -0.243544 -0.462710 -2.429197 -0.451577
2013-01-02  1.759290 -0.483506 -0.257713  1.979433
2013-01-03 -1.291636 -0.900783 -0.522704  1.027194
2013-01-04  0.625595  2.412614  1.010998 -0.098321
2013-01-05  0.315964  1.159868  0.109759 -0.321938
2013-01-06 -0.219220  1.028138 -1.717185 -0.006148

In [13]:
print(np.__version__)

1.15.4


In [14]:
z = np.zeros(10)

In [15]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
z[4] = 1

In [17]:
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
j = np.arange(50)

In [20]:
j[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [21]:
l = np.arange(9).reshape(3,3)

In [22]:
l

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
dato = '12-==00)()=009090¡''¡c'

In [24]:
dato

'12-==00)()=009090¡¡c'

In [25]:
import re


In [26]:
import re
dato = '12-345///6789-xññ'
re.sub('[^A-Za-z0-9]+', '', dato)
    

'123456789x'

In [27]:
nz = np.nonzero([1,2,0,0,4,0])

In [28]:
nz

(array([0, 1, 4], dtype=int32),)

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
import matplotlib.pyplot  as plt
import time

a = 0

tablero = np.arange(100).reshape(10,10)
listado = np.random.randint(200, size=10)
listadoOk = []

for i in range(len(tablero)):
    for j in tablero[i]:
        if listado[a] in tablero[i]:
            listadoOk.append(listado[a])
        a += 1
        if a > 9:
            a = 0
            
totalDatos = len(listadoOk)
fechas = pd.date_range(time.strftime('%Y %m %d'), periods = totalDatos)
fechas = fechas.format(formatter=lambda x: x.strftime('%Y%m%d'))
fechasDato = []

h = 0

for p in (fechas):
    fechasDato.append( [ fechas[h], listadoOk[h] ])
    h += 1
    
fechasDato

[['20190228', 23],
 ['20190301', 34],
 ['20190302', 33],
 ['20190303', 38],
 ['20190304', 64],
 ['20190305', 80],
 ['20190306', 80]]