<a id='arriba'></a>
# Practica de Numpy

- [Numerical Python / Realizar operaciones en paralelo](#numpy)
- [Creacion de distintos tipos de arreglos](#creacionArreglos)
- [Arreglos Indexados](#arreglosIndexados)
- [Slicing](#slicing)
- [Start Stop Step](#startStopStep)
- [Indices Negativos](#indicesNegativos)
- [Filtros Booleanos](#numpyBooleanos)
- [Filtros Universales](#filtrosUniversales)
- [Funciones de agregacion](#numpyAgregacion)
- <b>Otras funciones matematicas</b>
- [Numpy Add](#numpyAdd)
- [Numpy Subtract](#numpysubtract)
- [Numpy Multiply](#numpymultiply)
- [Numpy Divide](#numpydivide)
- [Numpy Logaddexp](#numpylogaddexp)
- [Numpy Logaddexp2](#numpylogaddexp2)
- [Numpy True Divide](#numpytrue_divide)
- [Numpy Floor Divide](#numpyfloor_divide)
- [Numpy Negative](#numpynegative)
- [Numpy Positive](#numpypositive)
- [Numpy Power](#numpypower)
- [Numpy Remainder](#numpyremainder)
- [Numpy Mod](#numpymod)
- [Numpy Fmod](#numpyfmod)
- <b>Funciones mateticas, trigonometricas, de comparación, flotantes y de bit-twiddling faltantes</b>
- <a href="https://docs.scipy.org/doc/numpy/reference/ufuncs.html" target="_blank"> Enlace externo </a>
- <b style="color: #e12f20;">Tutorial en youtube (El material es de un tutorial de la Universidad de Alicante, cubre varios temas, estos videos son los de Numpy.)</b>
- <a href="https://www.youtube.com/watch?v=UltVlYCacD0&index=5&list=PLoGFizEtm_6iheDXw2-8onKClyxgstBO1" target="_blank"> Arrays de NumPy - Parte 2.1 - Curso Python para científicos e ingenieros </a>
- <a href="https://www.youtube.com/watch?v=Sq7huaMBYHk&list=PLoGFizEtm_6iheDXw2-8onKClyxgstBO1&index=6" target="_blank"> Arrays de NumPy - Parte 2.2 - Curso Python para científicos e ingenieros </a>
- <a href="https://www.youtube.com/watch?v=LeMR3jlkk1Q&list=PLoGFizEtm_6iheDXw2-8onKClyxgstBO1&index=7" target="_blank"> Arrays de NumPy - Parte 2.3 - Curso Python para científicos e ingenieros </a>

In [1]:
import numpy as np

<a id='numpy' style="font-size: 25px; font-weight: bold;">- Numerical Python / Realizar operaciones en paralelo</a>

In [2]:
### Manejo simple de matrices Estructura n dimencional
data = np.random.rand(4,5)

In [3]:
data

array([[0.92946908, 0.49694637, 0.11664509, 0.78927383, 0.35533937],
       [0.16224279, 0.85628641, 0.20570963, 0.37074334, 0.65300526],
       [0.06028986, 0.40388407, 0.04001726, 0.4134164 , 0.21405391],
       [0.3132441 , 0.02685235, 0.9962706 , 0.40466323, 0.02056834]])

In [4]:
### Multiplicacion aplicada a todos los elementos
data * 9

array([[8.36522173, 4.47251736, 1.04980584, 7.10346448, 3.19805431],
       [1.46018514, 7.70657769, 1.85138665, 3.33669003, 5.87704735],
       [0.54260872, 3.63495666, 0.36015537, 3.72074757, 1.92648522],
       [2.81919686, 0.24167117, 8.96643541, 3.64196909, 0.18511503]])

In [5]:
### Suma de todos los elementos consigo mismo
data + data

array([[1.85893816, 0.99389275, 0.23329019, 1.57854766, 0.71067873],
       [0.32448559, 1.71257282, 0.41141926, 0.74148667, 1.30601052],
       [0.12057972, 0.80776815, 0.08003453, 0.82683279, 0.42810783],
       [0.62648819, 0.0537047 , 1.9925412 , 0.80932646, 0.04113667]])

In [6]:
### Estos arreglos de Numpy se pueden crear con arreglos de Python normales
dataDos = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]

In [7]:
arr = np.array(dataDos)

In [8]:
### Columnas por filas
arr.shape

(4, 3)

In [9]:
### Dimension array
arr.ndim

2

[Volver al listado](#arriba)

<a id='creacionArreglos' style="font-size: 25px; font-weight: bold;">- Creacion de distintos tipos de arreglos</a>

In [10]:
### Arreglos de ceros
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
### Arreglo de 10 elementos, empieza de 0
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
### Arreglo que vaya del 1 al 10 en base a 20 resultados
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

[Volver al listado](#arriba)

<a id='arreglosIndexados' style="font-size: 25px; font-weight: bold;">- Arreglos Indexados</a>

In [13]:
### Arreglo de 8 elementos empezando de 0
arr = np.arange(8)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
### Posicion 5 contando desde el cero
arr[5]

5

In [16]:
### Muesta los elementos del 2 al 5 sin incluir el 5 (El ultimo no se incluye)
arr[2:5]

array([2, 3, 4])

In [17]:
### Los dos puntos engloban a todo el arreglo, al igualarlo a 1 estoy cambiando todos los valores a 1
arr[:] = 1

In [18]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1])

[Volver al listado](#arriba)

<a id='slicing' style="font-size: 25px; font-weight: bold;">- Slicing</a>

In [19]:
### Array de Python
arrDos = [[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]]

In [20]:
### Array convertido a array de numpy
arrDosNumpy = np.array(arrDos)

In [21]:
### Columnas por filas
arrDosNumpy.shape

(5, 3)

In [22]:
### Dimensiones
arrDosNumpy.ndim

2

In [23]:
### Slicing simple
arrDosNumpy[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# De los arrays 1 y 2 todos los elementos que sigan dsp del primero
arrDosNumpy[:2, 1:]

array([[2, 3],
       [5, 6]])

In [25]:
### Del array 1 todos los elementos hasta el segundo sin incluirlo (Al igual que el array sus 
### elementos internos tambien empiezan desde cero)
arrDosNumpy[1, :2]

array([4, 5])

In [26]:
arrDosNumpy[1, :2] = 0

In [27]:
arrDosNumpy

array([[ 1,  2,  3],
       [ 0,  0,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

[Volver al listado](#arriba)

<a id='startStopStep' style="font-size: 25px; font-weight: bold;">- Start Stop Step</a>

In [28]:
arrStartStopStep = np.arange(10)

In [29]:
arrStartStopStep

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sistaxis <span style="font-weight: bold; color: black">x </span>[<span style="color: green; font-weight: bold;">start</span>:<span style="color: red; font-weight: bold;">stop</span>:<span style="color: blue; font-weight: bold;">step</span>]

In [30]:
### Se van a tomar los elementos desde start hasta stop saltando de a step elementos
arrStartStopStep[2:9:3]

array([2, 5, 8])

[Volver al listado](#arriba)

<a id='indicesNegativos' style="font-size: 25px; font-weight: bold;">- Indices Negativos</a>

In [31]:
arrIndicesNegativos = np.arange(10)

In [32]:
## Empeza del total del array menos -2 + 10 = 8 y llega a 10
arrIndicesNegativos[-2:10]

array([8, 9])

In [33]:
### Empeza del total del array menos -3 + 10 = 7 y llega al 3 restando de a un elemento
arrIndicesNegativos[-3:3:-1]

array([7, 6, 5, 4])

[Volver al listado](#arriba)

<a id='numpyBooleanos' style="font-size: 25px; font-weight: bold;">- Filtros Booleanos</a>

In [34]:
arrBooleano = np.random.randint(5, size=(3, 3))

In [35]:
arrBooleano

array([[0, 0, 4],
       [3, 0, 2],
       [3, 1, 0]])

In [36]:
### Verifica si cada elemento es menor a dos y devuelve True o False
arrBooleano < 2

array([[ True,  True, False],
       [False,  True, False],
       [False,  True,  True]])

In [37]:
### Devuelve los elementos que devuelven True en el filtro booleano
arrBooleano[arrBooleano < 2]

array([0, 0, 0, 1, 0])

In [38]:
arrBooleano > 0

array([[False, False,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [39]:
### Elementos mayores a cero
arrBooleano[arrBooleano > 0]

array([4, 3, 2, 3, 1])

[Volver al listado](#arriba)

<a id='filtrosUniversales' style="font-size: 25px; font-weight: bold;">- Filtros Universales</a>

In [40]:
universal = np.arange(10)
universal

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
### Obtener raiz cuadrada de cada uno de los elementos del array
np.sqrt(universal)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
### Devuelve el valor absoluto de cada uno de los elementos del arreglo
np.abs([-2, 1, -3])

array([2, 1, 3])

In [43]:
### Devuelve los caudrados de cada uno de los elementos 
np.square(universal)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [44]:
### Suma los elementos de cada array
np.add(universal, universal)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
### Seria igual a esto
np.add([0,1,2,3,4,5,6,7,8,9], [0,1,2,3,4,5,6,7,8,9])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

[Volver al listado](#arriba)

<a id='numpyAgregacion' style="font-size: 25px; font-weight: bold;">- Funciones de agregacion</a>

In [46]:
### Arreglo de 5 columnas x 5 filas con valores enteros que van del 0 al 5 de forma aleatoria
arrRandom = np.random.randint(5, size=(5, 5))

In [47]:
arrRandom

array([[3, 1, 2, 3, 4],
       [1, 3, 1, 3, 1],
       [3, 3, 3, 0, 3],
       [3, 2, 0, 3, 4],
       [1, 1, 4, 3, 3]])

In [48]:
### Promedio de todos sus valores
arrRandom.mean()

2.32

In [49]:
### Suma de todos los valores del arreglo
arrRandom.sum()

58

In [50]:
arrRandom.prod()

0

[Volver al listado](#arriba)

### Otras funciones

<a id='numpyAdd' style="font-size: 25px; font-weight: bold;">- Numpy Add</a>

In [51]:
arrAddUno = np.arange(1, 11)
arrAddDos = np.arange(10, 20)

In [52]:
arrAddUno, arrAddDos

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [53]:
### Suma los elementos de los arrays entre si
np.add(arrAddUno, arrAddDos)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

[Volver al listado](#arriba)

<a id='numpysubtract' style="font-size: 25px; font-weight: bold;">- Numpy Subtract</a>

In [54]:
arrSubUno = np.arange(1, 11)
arrSubDos = np.arange(10, 20)

In [55]:
arrSubUno, arrSubDos

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [56]:
### Resta los elementos de los arrays entre si
np.subtract(arrSubUno, arrSubDos)

array([-9, -9, -9, -9, -9, -9, -9, -9, -9, -9])

[Volver al listado](#arriba)

<a id='numpymultiply' style="font-size: 25px; font-weight: bold;">- Numpy Multiply</a>

In [57]:
arrMulUno = np.arange(1, 11)
arrMulDos = np.arange(10, 20)

In [58]:
arrMulUno, arrMulDos

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [59]:
### Multiplica los elementos de los arrays entre si
np.multiply(arrSubUno, arrSubDos)

array([ 10,  22,  36,  52,  70,  90, 112, 136, 162, 190])

[Volver al listado](#arriba)

<a id='numpydivide' style="font-size: 25px; font-weight: bold;">- Numpy Divide</a>

In [60]:
arrDivUno = np.arange(1, 11)
arrDivDos = np.arange(10, 20)

In [61]:
arrDivUno, arrDivDos

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [62]:
### Divide los elementos de los arrays entre si
np.true_divide(arrSubUno, arrSubDos)

array([0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286,
       0.4       , 0.4375    , 0.47058824, 0.5       , 0.52631579])

[Volver al listado](#arriba)

<a id='numpylogaddexp' style="font-size: 25px; font-weight: bold;">- Numpy Logaddexp</a>

In [63]:
logaddexpUno = np.log(1e-10)
logaddexpDos = np.log(5e-10)

In [64]:
logaddexpUno, logaddexpDos

(-23.025850929940457, -21.416413017506358)

In [65]:
### Logaritmo de la suma de exponenciaciones de las entradas
np.logaddexp(logaddexpUno, logaddexpDos)

-21.234091460712403

In [66]:
np.exp(np.logaddexp(logaddexpUno, logaddexpDos))

5.999999999999995e-10

[Volver al listado](#arriba)

<a id='numpylogaddexp2' style="font-size: 25px; font-weight: bold;">- Numpy Logaddexp2</a>

In [67]:
logaddexp2Uno = np.log(1e-10)
logaddexp2Dos = np.log(5e-10)

In [68]:
logaddexp2Uno, logaddexp2Dos

(-23.025850929940457, -21.416413017506358)

In [69]:
### Logaritmo de la suma de exponenciaciones de las entradas en base 2
np.logaddexp2(logaddexp2Uno, logaddexp2Dos)

-21.00745555381729

In [70]:
np.exp(np.logaddexp2(logaddexp2Uno, logaddexp2Dos))

7.526238457199767e-10

[Volver al listado](#arriba)

<a id='numpytrue_divide' style="font-size: 25px; font-weight: bold;">- Numpy True Divide</a>

In [71]:
trueDivide = np.arange(5)
trueDivide

array([0, 1, 2, 3, 4])

In [72]:
### Devuelve una division verdadera de las entradas, esta division ajusta el tipo de salida
### para presentar la mejor respuesta, independientemente de los tipos de entrada.
np.true_divide(trueDivide, 4)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

[Volver al listado](#arriba)

<a id='numpyfloor_divide' style="font-size: 25px; font-weight: bold;">- Numpy Floor Divide</a>

In [73]:
floorDivide = np.arange(5)
floorDivide

array([0, 1, 2, 3, 4])

In [74]:
### Devuelve el entero más grande, más pequeño o igual a la división de las entradas. 
###  Es equivalente al operador resto de Python 3 / 2 tiene de resto 1
np.floor_divide(floorDivide, 3)

array([0, 0, 0, 1, 1], dtype=int32)

<a id='numpynegative' style="font-size: 25px; font-weight: bold;">- Numpy Negative</a>

In [75]:
### Pasa a negativo los valores, en el ejemplo 1 positivo a negativo = 1 negativo, 
### 1 negativo a negativo = negativo x negativo = positivo = 1 positivo
np.negative([1.,-1.])

array([-1.,  1.])

[Volver al listado](#arriba)

<a id='numpypositive' style="font-size: 25px; font-weight: bold;">- Numpy Positive</a>

In [76]:
### Pasa a positivo los valores, en el ejemplo 1 positivo a positivo = 1 positivo, 
### 1 negativo a positivo = negativo x positivo = negativo = 1 negativo
np.positive([2.,-2.])

array([ 2., -2.])

[Volver al listado](#arriba)

<a id='numpypower' style="font-size: 25px; font-weight: bold;">- Numpy Power</a>

In [77]:
power = np.arange(10)

In [78]:
power

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
### Eleva a la potencia que le digamos a cada numero del array
np.power(power, 3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

[Volver al listado](#arriba)

<a id='numpyremainder' style="font-size: 25px; font-weight: bold;">- Numpy Remainder</a>

In [80]:
### Devuelve el resto de la division entre los elementos de los arrays
np.remainder([1, 4, 7], [1, 3, 5])

array([0, 1, 2], dtype=int32)

In [81]:
remainder = np.arange(10)

In [82]:
remainder

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.remainder(remainder, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

[Volver al listado](#arriba)

<a id='numpymod' style="font-size: 25px; font-weight: bold;">- Numpy Mod</a>

In [84]:
### Similar a Remainder (Arriba)
np.mod([1, 4, 7], [1, 3, 5])

array([0, 1, 2], dtype=int32)

[Volver al listado](#arriba)

<a id='numpyfmod' style="font-size: 25px; font-weight: bold;">- Numpy Fmod</a>

In [85]:
### Devuelve el resto de la división de elementos.

In [86]:
fmodUno = np.arange(1, 7).reshape(3, 2)

In [87]:
fmodUno

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
np.fmod(fmodUno, [2, 2])

array([[1, 0],
       [1, 0],
       [1, 0]], dtype=int32)

[Volver al listado](#arriba)